Sprint_9
amagmail/java-kanban pull request #4
Opened 2024-12-19 15:03 UTC by amagmail

Solution Http Api

2024-12-20 06:45 UTC, VadimZharkov commented on src/Task.java
Однозначным идентификатором задачи является его id, поэтому в equals и hashCode достаточно использовать только id

2024-12-20 06:49 UTC, VadimZharkov commented on src/HttpTaskServer.java
> +    public TaskManager taskManager;
Делая public мы нарушаем икапсуляцию. Зачем кому-то извне доступ к менеджеру?

2024-12-20 06:49 UTC, VadimZharkov commented on src/HttpTaskServer.java
> +    public HttpServer httpServer;
См. коммент выше

2024-12-20 06:51 UTC, VadimZharkov commented on src/TasksHandler.java
> +                case "GET":
Лучше сделать перечилимые для http методов и статусов и здесь их использовать

2024-12-20 06:56 UTC, VadimZharkov commented on src/TasksHandler.java
> +                        writeResponse(exchange, gson.toJson(tasks), 200);
Когда эндпоинт возвращает json лучше еще писать в респонс заголовок "Content-Type", "application/json;charset=utf-8"

2024-12-20 06:59 UTC, VadimZharkov commented on src/TasksHandler.java
> +                            String inputTitle;
Слишком длинный кусок кода в условии. Имеет смысл вынести в отдельный служебный метод.

2024-12-20 07:03 UTC, VadimZharkov requested changes
Можно улучшить.
Замечания в TasksHandler применимы и для остальных обработчиков.
Плюс, файлов в проекте становится все больше. Нужно улучшить структуру проекта. Сделай пакеты tasks и managers и распредели классы по ним.

2024-12-20 15:08 UTC, amagmail commented on src/Task.java
Исправил

2024-12-20 15:10 UTC, amagmail commented on src/HttpTaskServer.java
> +    public TaskManager taskManager;
Исправил

2024-12-20 15:10 UTC, amagmail commented on src/HttpTaskServer.java
> +    public HttpServer httpServer;
Исправил

2024-12-20 17:44 UTC, amagmail commented on src/TasksHandler.java
> +                case "GET":
Выполнено

2024-12-20 17:50 UTC, amagmail commented on src/TasksHandler.java
> +                        writeResponse(exchange, gson.toJson(tasks), 200);
Выполнено

2024-12-20 17:50 UTC, amagmail commented on src/TasksHandler.java
> +                            String inputTitle;
Выполнено

2024-12-20 19:46 UTC, amagmail commented
Приветствую Вадим. Спасибо за комментарии, принял к сведению, исправил.

2024-12-21 05:32 UTC, VadimZharkov approved these changes

2024-12-23 06:19 UTC, merged